### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by katjam** [TheLabCollective/vector#222]
## User story & Acceptance criteria
Trello card: https://trello.com/c/jzU3Bol8/20-vv-as-the-lab-collective-i-need-to-have-access-to-statistics-about-how-the-app-is-being-used-to-improve-the-game-as-proof-to-fun

### Implementation plan
- [ ] Add tracking snippet
- [ ] Add banner to start page (with close button)
- [ ] Add info about cookies text to credits page

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
