### ISSUE TITLE
Add 11 narrative videos to app

### ISSUE THREAD

**Issue by katjam** [TheLabCollective/vector#223]
## User story & Acceptance criteria
Trello card: https://trello.com/c/9mCfLd1a/119-add-videos-into-flow-bentley-has-doc

### Implementation notes
See also notes from https://trello.com/c/6FWwHVSL/117-release-10-kickoff-meeting-4-08-2022

### Implementation plan
- [x] Map out where videos go (https://www.dropbox.com/s/7qq6kfsoutnpx1q/Vector%20app%20AV%20index.xlsx?dl=0)
- [ ] #227
- [ ] #233
- [ ] #234
- [x] #225
- [x] Test on small medium and large screens
- [x] Check design with Nick
- [ ] Check if there are any accessibility improvements we could make
- [ ] #232
- [ ] #230 

### Videos
PROTOCOL: https://youtu.be/WI9u6WcT148
PIGS: https://youtu.be/d1ELMaewJg0
MOUSE: https://youtu.be/vVPMFMUxqY4
MACAWUE: https://youtu.be/tjAgZ6D-NQE
FISH: https://youtu.be/p_iXxYg90P8
BIOMATTER: https://youtu.be/kpHd9ckuqDo

CLIP8: https://youtu.be/GWAbWhnfiHA
CLIP12: https://youtu.be/YgEEqV6unQ0
CLIP7: https://youtu.be/NG4R937KIIk
CLIP11: https://youtu.be/pBaKD2nMKcw
CLIP13: https://youtu.be/cNqxfq7u3VI
INTROPART1: https://youtu.be/VB0y52wzNZU
CLIP6: https://youtu.be/LImnnzBhsio
CLIP3: https://youtu.be/ua6k4S6DdMw
CLIP9: https://youtu.be/03pCvR3FIMo
CLIP2: https://youtu.be/I6jcCd4ug0M
CLIP5: https://youtu.be/TfXMgJKuzjs
CLIP10: https://youtu.be/GcNjDFg9gzc
CLIP4: https://youtu.be/qD4bZA8thMU
INTROPART1: https://youtu.be/VB0y52wzNZU
INTROWITHAL: https://youtu.be/rztd_BIXyUQ

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**

**Comment by katjam** [comment]
Clip 3
![image](https://user-images.githubusercontent.com/861172/184670231-601bb0d5-d685-4f29-8141-8e8cbc1804c8.png)

**Comment by katjam** [comment]
closing as carded elsewhere
