### ISSUE TITLE
How can we make it less likely for broken paths and orphan content to occur?

### ISSUE THREAD

**Issue by katjam** [TheLabCollective/vector#78]
## User story & Acceptance criteria
As an editor adding or amending content or storylines, I want the `triggered_by` and `choices` values to be constrained so that i cannot create broken paths.

### Implementation notes
(eee) If I make an edit to content that breaks the app, the build will fail (TBC lots of different levels of "broken") - right now we never fail the build on `yarn generate` and can end up with empty content `Dict`s

### Implementation plan
- [x] rudimentary path checker https://github.com/TheLabCollective/vector/pull/171
- [ ] limit keywords
- [ ] look into benefit of using `Maybe field` vs just having some md files without the fields. See email vs message type for `choices` field
- [ ] #49 <--- implement better debugging and fail states for decoders
- [ ] Parse trigger paths for max 5 choices (excluding init, start, step) & ensure there is a valid path to every content item (ie. content that has the same path minus the last item + addition of choice that adds last item)
- [ ] If more than one piece of content triggered by same string, only one of them can contain choices
- [ ] more...

List Content:
- [x] that has no triggered_by (cannot be triggered)
- [x] that is hidden to some teams
- [ ] that contains invalid choice word
- [ ] that contains invalid triggered_by + choice

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**

**Comment by katjam** [comment]
Won't fix. Not planning to tinker with paths ever again... if we do, then we'll probably want to re-visit this.

**Comment by katjam** [comment]
Re-opening as #229 revealing we do have some broken paths

**Comment by katjam** [comment]
These are the problem paths at the moment:

**Choices that do not appear in any trigger**
None

**Content hidden from some teams or without trigger**
* Email is hidden from Ash, Birch, Cedar, Elm, Fir, Hawthorn, Juniper, Lime, Maple: [barry-mice-genetic](http://localhost:3000/admin/#/collections/email/entries/barry-mice-genetic)
* Email is hidden from Ash, Birch, Cedar, Fir, Hawthorn, Juniper, Lime, Maple, Oak: [barry-mice-not-susceptible-mac-fish](http://localhost:3000/admin/#/collections/email/entries/barry-mice-not-susceptible-mac-fish)
* Email is hidden from Birch, Cedar, Elm, Fir, Hawthorn, Juniper, Lime, Maple, Oak: [lisa-mice-too-susceptible](http://localhost:3000/admin/#/collections/email/entries/lisa-mice-too-susceptible)
* Email is hidden from Elm: [lisa-no-virus-uptake-mice](http://localhost:3000/admin/#/collections/email/entries/lisa-no-virus-uptake-mice)
* Email with empty triggered by: [lisa-no-virus-uptake-mice](http://localhost:3000/admin/#/collections/email/entries/lisa-no-virus-uptake-mice)

**Dead ends**
init|start|bio|biobank|feedback|score|step|pigs|limit|step
init|start|mice|stemcell|feedback|score|step|change|fish|adult|step|feedback|score|step
init|start|mice|stemcell|feedback|score|step|change|fish|embryo|step|feedback|score|step
init|step|maquaques-scale-3|fish
init|step|maquaques-scale-3|pigs
